@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Print employee's Details"

    usecase UCa as "Delete an employee's
    details"

    HR - UC4
    UC4 ..> UCa : include
    UCa - Database
}

@enduml